const testValue = [
  {
    code: '340000',
    name: '安徽省',
    nameAbbr: 'ahs',
    nameEn: 'anhuisheng',
    level: '100',
    children: [
      {
        code: '341300',
        name: '宿州市',
        nameAbbr: 'szs',
        nameEn: 'suzhoushi',
        level: '010',
        children: [
          {
            code: '341321',
            name: '砀山县',
            nameAbbr: 'dsx',
            nameEn: 'dangshanxian',
            level: '001',
            children: null,
          },
          {
            code: '341322',
            name: '萧县',
            nameAbbr: 'xx',
            nameEn: 'xiaoxian',
            level: '001',
            children: null,
          },
          {
            code: '341323',
            name: '灵璧县',
            nameAbbr: 'lbx',
            nameEn: 'lingbixian',
            level: '001',
            children: null,
          },
          {
            code: '341324',
            name: '泗县',
            nameAbbr: 'sx',
            nameEn: 'sixian',
            level: '001',
            children: null,
          },
          {
            code: '341301',
            name: '市辖区',
            nameAbbr: 'sxq',
            nameEn: 'shixiaqu',
            level: '001',
            children: null,
          },
          {
            code: '341302',
            name: '埇桥区',
            nameAbbr: 'yqq',
            nameEn: 'yongqiaoqu',
            level: '001',
            children: null,
          },
          {
            code: '341372',
            name: '宿州经济技术开发区',
            nameAbbr: 'szjjjskfq',
            nameEn: 'suzhoujingjijishukaifaqu',
            level: '001',
            children: null,
          },
          {
            code: '341371',
            name: '宿州马鞍山现代产业园区',
            nameAbbr: 'szmasxdcyyq',
            nameEn: 'suzhoumaanshanxiandaichanyeyuanqu',
            level: '001',
            children: null,
          },
        ],
      },
      {
        code: '340100',
        name: '合肥市',
        nameAbbr: 'hfs',
        nameEn: 'hefeishi',
        level: '010',
        children: [
          {
            code: '340122',
            name: '肥东县',
            nameAbbr: 'fdx',
            nameEn: 'feidongxian',
            level: '001',
            children: null,
          },
          {
            code: '340123',
            name: '肥西县',
            nameAbbr: 'fxx',
            nameEn: 'feixixian',
            level: '001',
            children: null,
          },
          {
            code: '340121',
            name: '长丰县',
            nameAbbr: 'zfx',
            nameEn: 'zhangfengxian',
            level: '001',
            children: null,
          },
          {
            code: '340124',
            name: '庐江县',
            nameAbbr: 'ljx',
            nameEn: 'lujiangxian',
            level: '001',
            children: null,
          },
          {
            code: '340111',
            name: '包河区',
            nameAbbr: 'bhq',
            nameEn: 'baohequ',
            level: '001',
            children: null,
          },
          {
            code: '340101',
            name: '市辖区',
            nameAbbr: 'sxq',
            nameEn: 'shixiaqu',
            level: '001',
            children: null,
          },
          {
            code: '340104',
            name: '蜀山区',
            nameAbbr: 'ssq',
            nameEn: 'shushanqu',
            level: '001',
            children: null,
          },
          {
            code: '340102',
            name: '瑶海区',
            nameAbbr: 'yhq',
            nameEn: 'yaohaiqu',
            level: '001',
            children: null,
          },
          {
            code: '340103',
            name: '庐阳区',
            nameAbbr: 'lyq',
            nameEn: 'luyangqu',
            level: '001',
            children: null,
          },
          {
            code: '340181',
            name: '巢湖市',
            nameAbbr: 'chs',
            nameEn: 'chaohushi',
            level: '001',
            children: null,
          },
          {
            code: '340173',
            name: '合肥新站高新技术产业开发区',
            nameAbbr: 'hfxzgxjscykfq',
            nameEn: 'hefeixinzhangaoxinjishuchanyekaifaqu',
            level: '001',
            children: null,
          },
          {
            code: '340171',
            name: '合肥高新技术产业开发区',
            nameAbbr: 'hfgxjscykfq',
            nameEn: 'hefeigaoxinjishuchanyekaifaqu',
            level: '001',
            children: null,
          },
          {
            code: '340172',
            name: '合肥经济技术开发区',
            nameAbbr: 'hfjjjskfq',
            nameEn: 'hefeijingjijishukaifaqu',
            level: '001',
            children: null,
          },
        ],
      },
      {
        code: '340600',
        name: '淮北市',
        nameAbbr: 'hbs',
        nameEn: 'huaibeishi',
        level: '010',
        children: [
          {
            code: '340621',
            name: '濉溪县',
            nameAbbr: 'sxx',
            nameEn: 'suixixian',
            level: '001',
            children: null,
          },
          {
            code: '340603',
            name: '相山区',
            nameAbbr: 'xsq',
            nameEn: 'xiangshanqu',
            level: '001',
            children: null,
          },
          {
            code: '340604',
            name: '烈山区',
            nameAbbr: 'lsq',
            nameEn: 'lieshanqu',
            level: '001',
            children: null,
          },
          {
            code: '340601',
            name: '市辖区',
            nameAbbr: 'sxq',
            nameEn: 'shixiaqu',
            level: '001',
            children: null,
          },
          {
            code: '340602',
            name: '杜集区',
            nameAbbr: 'djq',
            nameEn: 'dujiqu',
            level: '001',
            children: null,
          },
        ],
      },
      {
        code: '341100',
        name: '滁州市',
        nameAbbr: 'czs',
        nameEn: 'chuzhoushi',
        level: '010',
        children: [
          {
            code: '341181',
            name: '天长市',
            nameAbbr: 'tzs',
            nameEn: 'tianzhangshi',
            level: '001',
            children: null,
          },
          {
            code: '341182',
            name: '明光市',
            nameAbbr: 'mgs',
            nameEn: 'mingguangshi',
            level: '001',
            children: null,
          },
          {
            code: '341171',
            name: '苏滁现代产业园',
            nameAbbr: 'scxdcyy',
            nameEn: 'suchuxiandaichanyeyuan',
            level: '001',
            children: null,
          },
          {
            code: '341172',
            name: '滁州经济技术开发区',
            nameAbbr: 'czjjjskfq',
            nameEn: 'chuzhoujingjijishukaifaqu',
            level: '001',
            children: null,
          },
          {
            code: '341124',
            name: '全椒县',
            nameAbbr: 'qjx',
            nameEn: 'quanjiaoxian',
            level: '001',
            children: null,
          },
          {
            code: '341122',
            name: '来安县',
            nameAbbr: 'lax',
            nameEn: 'laianxian',
            level: '001',
            children: null,
          },
          {
            code: '341125',
            name: '定远县',
            nameAbbr: 'dyx',
            nameEn: 'dingyuanxian',
            level: '001',
            children: null,
          },
          {
            code: '341126',
            name: '凤阳县',
            nameAbbr: 'fyx',
            nameEn: 'fengyangxian',
            level: '001',
            children: null,
          },
          {
            code: '341101',
            name: '市辖区',
            nameAbbr: 'sxq',
            nameEn: 'shixiaqu',
            level: '001',
            children: null,
          },
          {
            code: '341102',
            name: '琅琊区',
            nameAbbr: 'lyq',
            nameEn: 'langyaqu',
            level: '001',
            children: null,
          },
          {
            code: '341103',
            name: '南谯区',
            nameAbbr: 'nqq',
            nameEn: 'nanqiaoqu',
            level: '001',
            children: null,
          },
        ],
      },
      {
        code: '341200',
        name: '阜阳市',
        nameAbbr: 'fys',
        nameEn: 'fuyangshi',
        level: '010',
        children: [
          {
            code: '341201',
            name: '市辖区',
            nameAbbr: 'sxq',
            nameEn: 'shixiaqu',
            level: '001',
            children: null,
          },
          {
            code: '341204',
            name: '颍泉区',
            nameAbbr: 'yqq',
            nameEn: 'yingquanqu',
            level: '001',
            children: null,
          },
          {
            code: '341202',
            name: '颍州区',
            nameAbbr: 'yzq',
            nameEn: 'yingzhouqu',
            level: '001',
            children: null,
          },
          {
            code: '341203',
            name: '颍东区',
            nameAbbr: 'ydq',
            nameEn: 'yingdongqu',
            level: '001',
            children: null,
          },
          {
            code: '341282',
            name: '界首市',
            nameAbbr: 'jss',
            nameEn: 'jieshoushi',
            level: '001',
            children: null,
          },
          {
            code: '341271',
            name: '阜阳合肥现代产业园区',
            nameAbbr: 'fyhfxdcyyq',
            nameEn: 'fuyanghefeixiandaichanyeyuanqu',
            level: '001',
            children: null,
          },
          {
            code: '341272',
            name: '阜阳经济技术开发区',
            nameAbbr: 'fyjjjskfq',
            nameEn: 'fuyangjingjijishukaifaqu',
            level: '001',
            children: null,
          },
          {
            code: '341222',
            name: '太和县',
            nameAbbr: 'thx',
            nameEn: 'taihexian',
            level: '001',
            children: null,
          },
          {
            code: '341221',
            name: '临泉县',
            nameAbbr: 'lqx',
            nameEn: 'linquanxian',
            level: '001',
            children: null,
          },
          {
            code: '341226',
            name: '颍上县',
            nameAbbr: 'ysx',
            nameEn: 'yingshangxian',
            level: '001',
            children: null,
          },
          {
            code: '341225',
            name: '阜南县',
            nameAbbr: 'fnx',
            nameEn: 'funanxian',
            level: '001',
            children: null,
          },
        ],
      },
      {
        code: '340700',
        name: '铜陵市',
        nameAbbr: 'tls',
        nameEn: 'tonglingshi',
        level: '010',
        children: [
          {
            code: '340722',
            name: '枞阳县',
            nameAbbr: 'zyx',
            nameEn: 'zongyangxian',
            level: '001',
            children: null,
          },
          {
            code: '340711',
            name: '郊区',
            nameAbbr: 'jq',
            nameEn: 'jiaoqu',
            level: '001',
            children: null,
          },
          {
            code: '340701',
            name: '市辖区',
            nameAbbr: 'sxq',
            nameEn: 'shixiaqu',
            level: '001',
            children: null,
          },
          {
            code: '340706',
            name: '义安区',
            nameAbbr: 'yaq',
            nameEn: 'yianqu',
            level: '001',
            children: null,
          },
          {
            code: '340705',
            name: '铜官区',
            nameAbbr: 'tgq',
            nameEn: 'tongguanqu',
            level: '001',
            children: null,
          },
        ],
      },
      {
        code: '340800',
        name: '安庆市',
        nameAbbr: 'aqs',
        nameEn: 'anqingshi',
        level: '010',
        children: [
          {
            code: '340881',
            name: '桐城市',
            nameAbbr: 'tcs',
            nameEn: 'tongchengshi',
            level: '001',
            children: null,
          },
          {
            code: '340871',
            name: '安徽安庆经济开发区',
            nameAbbr: 'ahaqjjkfq',
            nameEn: 'anhuianqingjingjikaifaqu',
            level: '001',
            children: null,
          },
          {
            code: '340824',
            name: '潜山县',
            nameAbbr: 'qsx',
            nameEn: 'qianshanxian',
            level: '001',
            children: null,
          },
          {
            code: '340822',
            name: '怀宁县',
            nameAbbr: 'hnx',
            nameEn: 'huainingxian',
            level: '001',
            children: null,
          },
          {
            code: '340827',
            name: '望江县',
            nameAbbr: 'wjx',
            nameEn: 'wangjiangxian',
            level: '001',
            children: null,
          },
          {
            code: '340828',
            name: '岳西县',
            nameAbbr: 'yxx',
            nameEn: 'yuexixian',
            level: '001',
            children: null,
          },
          {
            code: '340825',
            name: '太湖县',
            nameAbbr: 'thx',
            nameEn: 'taihuxian',
            level: '001',
            children: null,
          },
          {
            code: '340826',
            name: '宿松县',
            nameAbbr: 'ssx',
            nameEn: 'susongxian',
            level: '001',
            children: null,
          },
          {
            code: '340811',
            name: '宜秀区',
            nameAbbr: 'yxq',
            nameEn: 'yixiuqu',
            level: '001',
            children: null,
          },
          {
            code: '340801',
            name: '市辖区',
            nameAbbr: 'sxq',
            nameEn: 'shixiaqu',
            level: '001',
            children: null,
          },
          {
            code: '340802',
            name: '迎江区',
            nameAbbr: 'yjq',
            nameEn: 'yingjiangqu',
            level: '001',
            children: null,
          },
          {
            code: '340803',
            name: '大观区',
            nameAbbr: 'dgq',
            nameEn: 'daguanqu',
            level: '001',
            children: null,
          },
        ],
      },
      {
        code: '340400',
        name: '淮南市',
        nameAbbr: 'hns',
        nameEn: 'huainanshi',
        level: '010',
        children: [
          {
            code: '340421',
            name: '凤台县',
            nameAbbr: 'ftx',
            nameEn: 'fengtaixian',
            level: '001',
            children: null,
          },
          {
            code: '340422',
            name: '寿县',
            nameAbbr: 'sx',
            nameEn: 'shouxian',
            level: '001',
            children: null,
          },
          {
            code: '340405',
            name: '八公山区',
            nameAbbr: 'bgsq',
            nameEn: 'bagongshanqu',
            level: '001',
            children: null,
          },
          {
            code: '340406',
            name: '潘集区',
            nameAbbr: 'pjq',
            nameEn: 'panjiqu',
            level: '001',
            children: null,
          },
          {
            code: '340403',
            name: '田家庵区',
            nameAbbr: 'tjaq',
            nameEn: 'tianjiaanqu',
            level: '001',
            children: null,
          },
          {
            code: '340404',
            name: '谢家集区',
            nameAbbr: 'xjjq',
            nameEn: 'xiejiajiqu',
            level: '001',
            children: null,
          },
          {
            code: '340401',
            name: '市辖区',
            nameAbbr: 'sxq',
            nameEn: 'shixiaqu',
            level: '001',
            children: null,
          },
          {
            code: '340402',
            name: '大通区',
            nameAbbr: 'dtq',
            nameEn: 'datongqu',
            level: '001',
            children: null,
          },
        ],
      },
      {
        code: '341700',
        name: '池州市',
        nameAbbr: 'czs',
        nameEn: 'chizhoushi',
        level: '010',
        children: [
          {
            code: '341723',
            name: '青阳县',
            nameAbbr: 'qyx',
            nameEn: 'qingyangxian',
            level: '001',
            children: null,
          },
          {
            code: '341722',
            name: '石台县',
            nameAbbr: 'stx',
            nameEn: 'shitaixian',
            level: '001',
            children: null,
          },
          {
            code: '341721',
            name: '东至县',
            nameAbbr: 'dzx',
            nameEn: 'dongzhixian',
            level: '001',
            children: null,
          },
          {
            code: '341702',
            name: '贵池区',
            nameAbbr: 'gcq',
            nameEn: 'guichiqu',
            level: '001',
            children: null,
          },
          {
            code: '341701',
            name: '市辖区',
            nameAbbr: 'sxq',
            nameEn: 'shixiaqu',
            level: '001',
            children: null,
          },
        ],
      },
      {
        code: '340500',
        name: '马鞍山市',
        nameAbbr: 'mass',
        nameEn: 'maanshanshi',
        level: '010',
        children: [
          {
            code: '340522',
            name: '含山县',
            nameAbbr: 'hsx',
            nameEn: 'hanshanxian',
            level: '001',
            children: null,
          },
          {
            code: '340523',
            name: '和县',
            nameAbbr: 'hx',
            nameEn: 'hexian',
            level: '001',
            children: null,
          },
          {
            code: '340521',
            name: '当涂县',
            nameAbbr: 'dtx',
            nameEn: 'dangtuxian',
            level: '001',
            children: null,
          },
          {
            code: '340504',
            name: '雨山区',
            nameAbbr: 'ysq',
            nameEn: 'yushanqu',
            level: '001',
            children: null,
          },
          {
            code: '340503',
            name: '花山区',
            nameAbbr: 'hsq',
            nameEn: 'huashanqu',
            level: '001',
            children: null,
          },
          {
            code: '340506',
            name: '博望区',
            nameAbbr: 'bwq',
            nameEn: 'bowangqu',
            level: '001',
            children: null,
          },
          {
            code: '340501',
            name: '市辖区',
            nameAbbr: 'sxq',
            nameEn: 'shixiaqu',
            level: '001',
            children: null,
          },
        ],
      },
      {
        code: '341800',
        name: '宣城市',
        nameAbbr: 'xcs',
        nameEn: 'xuanchengshi',
        level: '010',
        children: [
          {
            code: '341881',
            name: '宁国市',
            nameAbbr: 'ngs',
            nameEn: 'ningguoshi',
            level: '001',
            children: null,
          },
          {
            code: '341871',
            name: '宣城市经济开发区',
            nameAbbr: 'xcsjjkfq',
            nameEn: 'xuanchengshijingjikaifaqu',
            level: '001',
            children: null,
          },
          {
            code: '341825',
            name: '旌德县',
            nameAbbr: 'jdx',
            nameEn: 'jingdexian',
            level: '001',
            children: null,
          },
          {
            code: '341824',
            name: '绩溪县',
            nameAbbr: 'jxx',
            nameEn: 'jixixian',
            level: '001',
            children: null,
          },
          {
            code: '341823',
            name: '泾县',
            nameAbbr: 'jx',
            nameEn: 'jingxian',
            level: '001',
            children: null,
          },
          {
            code: '341822',
            name: '广德县',
            nameAbbr: 'gdx',
            nameEn: 'guangdexian',
            level: '001',
            children: null,
          },
          {
            code: '341821',
            name: '郎溪县',
            nameAbbr: 'lxx',
            nameEn: 'langxixian',
            level: '001',
            children: null,
          },
          {
            code: '341802',
            name: '宣州区',
            nameAbbr: 'xzq',
            nameEn: 'xuanzhouqu',
            level: '001',
            children: null,
          },
          {
            code: '341801',
            name: '市辖区',
            nameAbbr: 'sxq',
            nameEn: 'shixiaqu',
            level: '001',
            children: null,
          },
        ],
      },
      {
        code: '341000',
        name: '黄山市',
        nameAbbr: 'hss',
        nameEn: 'huangshanshi',
        level: '010',
        children: [
          {
            code: '341024',
            name: '祁门县',
            nameAbbr: 'qmx',
            nameEn: 'qimenxian',
            level: '001',
            children: null,
          },
          {
            code: '341022',
            name: '休宁县',
            nameAbbr: 'xnx',
            nameEn: 'xiuningxian',
            level: '001',
            children: null,
          },
          {
            code: '341023',
            name: '黟县',
            nameAbbr: 'yx',
            nameEn: 'yixian',
            level: '001',
            children: null,
          },
          {
            code: '341021',
            name: '歙县',
            nameAbbr: 'sx',
            nameEn: 'shexian',
            level: '001',
            children: null,
          },
          {
            code: '341002',
            name: '屯溪区',
            nameAbbr: 'txq',
            nameEn: 'tunxiqu',
            level: '001',
            children: null,
          },
          {
            code: '341003',
            name: '黄山区',
            nameAbbr: 'hsq',
            nameEn: 'huangshanqu',
            level: '001',
            children: null,
          },
          {
            code: '341001',
            name: '市辖区',
            nameAbbr: 'sxq',
            nameEn: 'shixiaqu',
            level: '001',
            children: null,
          },
          {
            code: '341004',
            name: '徽州区',
            nameAbbr: 'hzq',
            nameEn: 'huizhouqu',
            level: '001',
            children: null,
          },
        ],
      },
      {
        code: '340200',
        name: '芜湖市',
        nameAbbr: 'whs',
        nameEn: 'wuhushi',
        level: '010',
        children: [
          {
            code: '340221',
            name: '芜湖县',
            nameAbbr: 'whx',
            nameEn: 'wuhuxian',
            level: '001',
            children: null,
          },
          {
            code: '340222',
            name: '繁昌县',
            nameAbbr: 'fcx',
            nameEn: 'fanchangxian',
            level: '001',
            children: null,
          },
          {
            code: '340225',
            name: '无为县',
            nameAbbr: 'wwx',
            nameEn: 'wuweixian',
            level: '001',
            children: null,
          },
          {
            code: '340223',
            name: '南陵县',
            nameAbbr: 'nlx',
            nameEn: 'nanlingxian',
            level: '001',
            children: null,
          },
          {
            code: '340207',
            name: '鸠江区',
            nameAbbr: 'jjq',
            nameEn: 'jiujiangqu',
            level: '001',
            children: null,
          },
          {
            code: '340208',
            name: '三山区',
            nameAbbr: 'ssq',
            nameEn: 'sanshanqu',
            level: '001',
            children: null,
          },
          {
            code: '340203',
            name: '弋江区',
            nameAbbr: 'yjq',
            nameEn: 'yijiangqu',
            level: '001',
            children: null,
          },
          {
            code: '340201',
            name: '市辖区',
            nameAbbr: 'sxq',
            nameEn: 'shixiaqu',
            level: '001',
            children: null,
          },
          {
            code: '340202',
            name: '镜湖区',
            nameAbbr: 'jhq',
            nameEn: 'jinghuqu',
            level: '001',
            children: null,
          },
          {
            code: '340272',
            name: '安徽芜湖长江大桥经济开发区',
            nameAbbr: 'ahwhzjdqjjkfq',
            nameEn: 'anhuiwuhuzhangjiangdaqiaojingjikaifaqu',
            level: '001',
            children: null,
          },
          {
            code: '340271',
            name: '芜湖经济技术开发区',
            nameAbbr: 'whjjjskfq',
            nameEn: 'wuhujingjijishukaifaqu',
            level: '001',
            children: null,
          },
        ],
      },
      {
        code: '341500',
        name: '六安市',
        nameAbbr: 'las',
        nameEn: 'liuanshi',
        level: '010',
        children: [
          {
            code: '341525',
            name: '霍山县',
            nameAbbr: 'hsx',
            nameEn: 'huoshanxian',
            level: '001',
            children: null,
          },
          {
            code: '341524',
            name: '金寨县',
            nameAbbr: 'jzx',
            nameEn: 'jinzhaixian',
            level: '001',
            children: null,
          },
          {
            code: '341523',
            name: '舒城县',
            nameAbbr: 'scx',
            nameEn: 'shuchengxian',
            level: '001',
            children: null,
          },
          {
            code: '341522',
            name: '霍邱县',
            nameAbbr: 'hqx',
            nameEn: 'huoqiuxian',
            level: '001',
            children: null,
          },
          {
            code: '341504',
            name: '叶集区',
            nameAbbr: 'yjq',
            nameEn: 'yejiqu',
            level: '001',
            children: null,
          },
          {
            code: '341503',
            name: '裕安区',
            nameAbbr: 'yaq',
            nameEn: 'yuanqu',
            level: '001',
            children: null,
          },
          {
            code: '341502',
            name: '金安区',
            nameAbbr: 'jaq',
            nameEn: 'jinanqu',
            level: '001',
            children: null,
          },
          {
            code: '341501',
            name: '市辖区',
            nameAbbr: 'sxq',
            nameEn: 'shixiaqu',
            level: '001',
            children: null,
          },
        ],
      },
      {
        code: '340300',
        name: '蚌埠市',
        nameAbbr: 'bbs',
        nameEn: 'bangbushi',
        level: '010',
        children: [
          {
            code: '340371',
            name: '蚌埠市高新技术开发区',
            nameAbbr: 'bbsgxjskfq',
            nameEn: 'bangbushigaoxinjishukaifaqu',
            level: '001',
            children: null,
          },
          {
            code: '340372',
            name: '蚌埠市经济开发区',
            nameAbbr: 'bbsjjkfq',
            nameEn: 'bangbushijingjikaifaqu',
            level: '001',
            children: null,
          },
          {
            code: '340321',
            name: '怀远县',
            nameAbbr: 'hyx',
            nameEn: 'huaiyuanxian',
            level: '001',
            children: null,
          },
          {
            code: '340322',
            name: '五河县',
            nameAbbr: 'whx',
            nameEn: 'wuhexian',
            level: '001',
            children: null,
          },
          {
            code: '340323',
            name: '固镇县',
            nameAbbr: 'gzx',
            nameEn: 'guzhenxian',
            level: '001',
            children: null,
          },
          {
            code: '340311',
            name: '淮上区',
            nameAbbr: 'hsq',
            nameEn: 'huaishangqu',
            level: '001',
            children: null,
          },
          {
            code: '340304',
            name: '禹会区',
            nameAbbr: 'yhq',
            nameEn: 'yuhuiqu',
            level: '001',
            children: null,
          },
          {
            code: '340302',
            name: '龙子湖区',
            nameAbbr: 'lzhq',
            nameEn: 'longzihuqu',
            level: '001',
            children: null,
          },
          {
            code: '340303',
            name: '蚌山区',
            nameAbbr: 'bsq',
            nameEn: 'bangshanqu',
            level: '001',
            children: null,
          },
          {
            code: '340301',
            name: '市辖区',
            nameAbbr: 'sxq',
            nameEn: 'shixiaqu',
            level: '001',
            children: null,
          },
        ],
      },
      {
        code: '341600',
        name: '亳州市',
        nameAbbr: 'bzs',
        nameEn: 'bozhoushi',
        level: '010',
        children: [
          {
            code: '341623',
            name: '利辛县',
            nameAbbr: 'lxx',
            nameEn: 'lixinxian',
            level: '001',
            children: null,
          },
          {
            code: '341622',
            name: '蒙城县',
            nameAbbr: 'mcx',
            nameEn: 'mengchengxian',
            level: '001',
            children: null,
          },
          {
            code: '341621',
            name: '涡阳县',
            nameAbbr: 'wyx',
            nameEn: 'woyangxian',
            level: '001',
            children: null,
          },
          {
            code: '341602',
            name: '谯城区',
            nameAbbr: 'qcq',
            nameEn: 'qiaochengqu',
            level: '001',
            children: null,
          },
          {
            code: '341601',
            name: '市辖区',
            nameAbbr: 'sxq',
            nameEn: 'shixiaqu',
            level: '001',
            children: null,
          },
        ],
      },
    ],
  },
  {
    code: '520000',
    name: '贵州省',
    nameAbbr: 'gzs',
    nameEn: 'guizhousheng',
    level: '100',
    children: [
      {
        code: '522700',
        name: '黔南布依族苗族自治州',
        nameAbbr: 'qnbyzmzzzz',
        nameEn: 'qiannanbuyizumiaozuzizhizhou',
        level: '010',
        children: [
          {
            code: '522728',
            name: '罗甸县',
            nameAbbr: 'ldx',
            nameEn: 'luodianxian',
            level: '001',
            children: null,
          },
          {
            code: '522729',
            name: '长顺县',
            nameAbbr: 'zsx',
            nameEn: 'zhangshunxian',
            level: '001',
            children: null,
          },
          {
            code: '522722',
            name: '荔波县',
            nameAbbr: 'lbx',
            nameEn: 'liboxian',
            level: '001',
            children: null,
          },
          {
            code: '522723',
            name: '贵定县',
            nameAbbr: 'gdx',
            nameEn: 'guidingxian',
            level: '001',
            children: null,
          },
          {
            code: '522725',
            name: '瓮安县',
            nameAbbr: 'wax',
            nameEn: 'wenganxian',
            level: '001',
            children: null,
          },
          {
            code: '522726',
            name: '独山县',
            nameAbbr: 'dsx',
            nameEn: 'dushanxian',
            level: '001',
            children: null,
          },
          {
            code: '522727',
            name: '平塘县',
            nameAbbr: 'ptx',
            nameEn: 'pingtangxian',
            level: '001',
            children: null,
          },
          {
            code: '522730',
            name: '龙里县',
            nameAbbr: 'llx',
            nameEn: 'longlixian',
            level: '001',
            children: null,
          },
          {
            code: '522701',
            name: '都匀市',
            nameAbbr: 'dys',
            nameEn: 'douyunshi',
            level: '001',
            children: null,
          },
          {
            code: '522702',
            name: '福泉市',
            nameAbbr: 'fqs',
            nameEn: 'fuquanshi',
            level: '001',
            children: null,
          },
          {
            code: '522731',
            name: '惠水县',
            nameAbbr: 'hsx',
            nameEn: 'huishuixian',
            level: '001',
            children: null,
          },
          {
            code: '522732',
            name: '三都水族自治县',
            nameAbbr: 'sdszzzx',
            nameEn: 'sandoushuizuzizhixian',
            level: '001',
            children: null,
          },
        ],
      },
      {
        code: '520100',
        name: '贵阳市',
        nameAbbr: 'gys',
        nameEn: 'guiyangshi',
        level: '010',
        children: [
          {
            code: '520101',
            name: '市辖区',
            nameAbbr: 'sxq',
            nameEn: 'shixiaqu',
            level: '001',
            children: null,
          },
          {
            code: '520103',
            name: '云岩区',
            nameAbbr: 'yyq',
            nameEn: 'yunyanqu',
            level: '001',
            children: null,
          },
          {
            code: '520102',
            name: '南明区',
            nameAbbr: 'nmq',
            nameEn: 'nanmingqu',
            level: '001',
            children: null,
          },
          {
            code: '520112',
            name: '乌当区',
            nameAbbr: 'wdq',
            nameEn: 'wudangqu',
            level: '001',
            children: null,
          },
          {
            code: '520111',
            name: '花溪区',
            nameAbbr: 'hxq',
            nameEn: 'huaxiqu',
            level: '001',
            children: null,
          },
          {
            code: '520113',
            name: '白云区',
            nameAbbr: 'byq',
            nameEn: 'baiyunqu',
            level: '001',
            children: null,
          },
          {
            code: '520115',
            name: '观山湖区',
            nameAbbr: 'gshq',
            nameEn: 'guanshanhuqu',
            level: '001',
            children: null,
          },
          {
            code: '520121',
            name: '开阳县',
            nameAbbr: 'kyx',
            nameEn: 'kaiyangxian',
            level: '001',
            children: null,
          },
          {
            code: '520122',
            name: '息烽县',
            nameAbbr: 'xfx',
            nameEn: 'xifengxian',
            level: '001',
            children: null,
          },
          {
            code: '520123',
            name: '修文县',
            nameAbbr: 'xwx',
            nameEn: 'xiuwenxian',
            level: '001',
            children: null,
          },
          {
            code: '520181',
            name: '清镇市',
            nameAbbr: 'qzs',
            nameEn: 'qingzhenshi',
            level: '001',
            children: null,
          },
        ],
      },
      {
        code: '522600',
        name: '黔东南苗族侗族自治州',
        nameAbbr: 'qdnmzdzzzz',
        nameEn: 'qiandongnanmiaozudongzuzizhizhou',
        level: '010',
        children: [
          {
            code: '522601',
            name: '凯里市',
            nameAbbr: 'kls',
            nameEn: 'kailishi',
            level: '001',
            children: null,
          },
          {
            code: '522632',
            name: '榕江县',
            nameAbbr: 'rjx',
            nameEn: 'rongjiangxian',
            level: '001',
            children: null,
          },
          {
            code: '522633',
            name: '从江县',
            nameAbbr: 'cjx',
            nameEn: 'congjiangxian',
            level: '001',
            children: null,
          },
          {
            code: '522634',
            name: '雷山县',
            nameAbbr: 'lsx',
            nameEn: 'leishanxian',
            level: '001',
            children: null,
          },
          {
            code: '522635',
            name: '麻江县',
            nameAbbr: 'mjx',
            nameEn: 'majiangxian',
            level: '001',
            children: null,
          },
          {
            code: '522636',
            name: '丹寨县',
            nameAbbr: 'dzx',
            nameEn: 'danzhaixian',
            level: '001',
            children: null,
          },
          {
            code: '522629',
            name: '剑河县',
            nameAbbr: 'jhx',
            nameEn: 'jianhexian',
            level: '001',
            children: null,
          },
          {
            code: '522622',
            name: '黄平县',
            nameAbbr: 'hpx',
            nameEn: 'huangpingxian',
            level: '001',
            children: null,
          },
          {
            code: '522623',
            name: '施秉县',
            nameAbbr: 'sbx',
            nameEn: 'shibingxian',
            level: '001',
            children: null,
          },
          {
            code: '522624',
            name: '三穗县',
            nameAbbr: 'ssx',
            nameEn: 'sansuixian',
            level: '001',
            children: null,
          },
          {
            code: '522625',
            name: '镇远县',
            nameAbbr: 'zyx',
            nameEn: 'zhenyuanxian',
            level: '001',
            children: null,
          },
          {
            code: '522626',
            name: '岑巩县',
            nameAbbr: 'cgx',
            nameEn: 'cengongxian',
            level: '001',
            children: null,
          },
          {
            code: '522627',
            name: '天柱县',
            nameAbbr: 'tzx',
            nameEn: 'tianzhuxian',
            level: '001',
            children: null,
          },
          {
            code: '522628',
            name: '锦屏县',
            nameAbbr: 'jpx',
            nameEn: 'jinpingxian',
            level: '001',
            children: null,
          },
          {
            code: '522630',
            name: '台江县',
            nameAbbr: 'tjx',
            nameEn: 'taijiangxian',
            level: '001',
            children: null,
          },
          {
            code: '522631',
            name: '黎平县',
            nameAbbr: 'lpx',
            nameEn: 'lipingxian',
            level: '001',
            children: null,
          },
        ],
      },
      {
        code: '522300',
        name: '黔西南布依族苗族自治州',
        nameAbbr: 'qxnbyzmzzzz',
        nameEn: 'qianxinanbuyizumiaozuzizhizhou',
        level: '010',
        children: [
          {
            code: '522322',
            name: '兴仁县',
            nameAbbr: 'xrx',
            nameEn: 'xingrenxian',
            level: '001',
            children: null,
          },
          {
            code: '522323',
            name: '普安县',
            nameAbbr: 'pax',
            nameEn: 'puanxian',
            level: '001',
            children: null,
          },
          {
            code: '522324',
            name: '晴隆县',
            nameAbbr: 'qlx',
            nameEn: 'qinglongxian',
            level: '001',
            children: null,
          },
          {
            code: '522325',
            name: '贞丰县',
            nameAbbr: 'zfx',
            nameEn: 'zhenfengxian',
            level: '001',
            children: null,
          },
          {
            code: '522326',
            name: '望谟县',
            nameAbbr: 'wmx',
            nameEn: 'wangmoxian',
            level: '001',
            children: null,
          },
          {
            code: '522327',
            name: '册亨县',
            nameAbbr: 'chx',
            nameEn: 'cehengxian',
            level: '001',
            children: null,
          },
          {
            code: '522328',
            name: '安龙县',
            nameAbbr: 'alx',
            nameEn: 'anlongxian',
            level: '001',
            children: null,
          },
          {
            code: '522301',
            name: '兴义市',
            nameAbbr: 'xys',
            nameEn: 'xingyishi',
            level: '001',
            children: null,
          },
        ],
      },
      {
        code: '520600',
        name: '铜仁市',
        nameAbbr: 'trs',
        nameEn: 'tongrenshi',
        level: '010',
        children: [
          {
            code: '520627',
            name: '沿河土家族自治县',
            nameAbbr: 'yhtjzzzx',
            nameEn: 'yanhetujiazuzizhixian',
            level: '001',
            children: null,
          },
          {
            code: '520628',
            name: '松桃苗族自治县',
            nameAbbr: 'stmzzzx',
            nameEn: 'songtaomiaozuzizhixian',
            level: '001',
            children: null,
          },
          {
            code: '520621',
            name: '江口县',
            nameAbbr: 'jkx',
            nameEn: 'jiangkouxian',
            level: '001',
            children: null,
          },
          {
            code: '520622',
            name: '玉屏侗族自治县',
            nameAbbr: 'ypdzzzx',
            nameEn: 'yupingdongzuzizhixian',
            level: '001',
            children: null,
          },
          {
            code: '520623',
            name: '石阡县',
            nameAbbr: 'sqx',
            nameEn: 'shiqianxian',
            level: '001',
            children: null,
          },
          {
            code: '520624',
            name: '思南县',
            nameAbbr: 'snx',
            nameEn: 'sinanxian',
            level: '001',
            children: null,
          },
          {
            code: '520625',
            name: '印江土家族苗族自治县',
            nameAbbr: 'yjtjzmzzzx',
            nameEn: 'yinjiangtujiazumiaozuzizhixian',
            level: '001',
            children: null,
          },
          {
            code: '520626',
            name: '德江县',
            nameAbbr: 'djx',
            nameEn: 'dejiangxian',
            level: '001',
            children: null,
          },
          {
            code: '520601',
            name: '市辖区',
            nameAbbr: 'sxq',
            nameEn: 'shixiaqu',
            level: '001',
            children: null,
          },
          {
            code: '520602',
            name: '碧江区',
            nameAbbr: 'bjq',
            nameEn: 'bijiangqu',
            level: '001',
            children: null,
          },
          {
            code: '520603',
            name: '万山区',
            nameAbbr: 'wsq',
            nameEn: 'wanshanqu',
            level: '001',
            children: null,
          },
        ],
      },
      {
        code: '520500',
        name: '毕节市',
        nameAbbr: 'bjs',
        nameEn: 'bijieshi',
        level: '010',
        children: [
          {
            code: '520521',
            name: '大方县',
            nameAbbr: 'dfx',
            nameEn: 'dafangxian',
            level: '001',
            children: null,
          },
          {
            code: '520522',
            name: '黔西县',
            nameAbbr: 'qxx',
            nameEn: 'qianxixian',
            level: '001',
            children: null,
          },
          {
            code: '520523',
            name: '金沙县',
            nameAbbr: 'jsx',
            nameEn: 'jinshaxian',
            level: '001',
            children: null,
          },
          {
            code: '520524',
            name: '织金县',
            nameAbbr: 'zjx',
            nameEn: 'zhijinxian',
            level: '001',
            children: null,
          },
          {
            code: '520525',
            name: '纳雍县',
            nameAbbr: 'nyx',
            nameEn: 'nayongxian',
            level: '001',
            children: null,
          },
          {
            code: '520526',
            name: '威宁彝族回族苗族自治县',
            nameAbbr: 'wnyzhzmzzzx',
            nameEn: 'weiningyizuhuizumiaozuzizhixian',
            level: '001',
            children: null,
          },
          {
            code: '520527',
            name: '赫章县',
            nameAbbr: 'hzx',
            nameEn: 'hezhangxian',
            level: '001',
            children: null,
          },
          {
            code: '520501',
            name: '市辖区',
            nameAbbr: 'sxq',
            nameEn: 'shixiaqu',
            level: '001',
            children: null,
          },
          {
            code: '520502',
            name: '七星关区',
            nameAbbr: 'qxgq',
            nameEn: 'qixingguanqu',
            level: '001',
            children: null,
          },
        ],
      },
      {
        code: '520400',
        name: '安顺市',
        nameAbbr: 'ass',
        nameEn: 'anshunshi',
        level: '010',
        children: [
          {
            code: '520422',
            name: '普定县',
            nameAbbr: 'pdx',
            nameEn: 'pudingxian',
            level: '001',
            children: null,
          },
          {
            code: '520423',
            name: '镇宁布依族苗族自治县',
            nameAbbr: 'znbyzmzzzx',
            nameEn: 'zhenningbuyizumiaozuzizhixian',
            level: '001',
            children: null,
          },
          {
            code: '520424',
            name: '关岭布依族苗族自治县',
            nameAbbr: 'glbyzmzzzx',
            nameEn: 'guanlingbuyizumiaozuzizhixian',
            level: '001',
            children: null,
          },
          {
            code: '520425',
            name: '紫云苗族布依族自治县',
            nameAbbr: 'zymzbyzzzx',
            nameEn: 'ziyunmiaozubuyizuzizhixian',
            level: '001',
            children: null,
          },
          {
            code: '520401',
            name: '市辖区',
            nameAbbr: 'sxq',
            nameEn: 'shixiaqu',
            level: '001',
            children: null,
          },
          {
            code: '520402',
            name: '西秀区',
            nameAbbr: 'xxq',
            nameEn: 'xixiuqu',
            level: '001',
            children: null,
          },
          {
            code: '520403',
            name: '平坝区',
            nameAbbr: 'pbq',
            nameEn: 'pingbaqu',
            level: '001',
            children: null,
          },
        ],
      },
      {
        code: '520300',
        name: '遵义市',
        nameAbbr: 'zys',
        nameEn: 'zunyishi',
        level: '010',
        children: [
          {
            code: '520381',
            name: '赤水市',
            nameAbbr: 'css',
            nameEn: 'chishuishi',
            level: '001',
            children: null,
          },
          {
            code: '520382',
            name: '仁怀市',
            nameAbbr: 'rhs',
            nameEn: 'renhuaishi',
            level: '001',
            children: null,
          },
          {
            code: '520301',
            name: '市辖区',
            nameAbbr: 'sxq',
            nameEn: 'shixiaqu',
            level: '001',
            children: null,
          },
          {
            code: '520302',
            name: '红花岗区',
            nameAbbr: 'hhgq',
            nameEn: 'honghuagangqu',
            level: '001',
            children: null,
          },
          {
            code: '520303',
            name: '汇川区',
            nameAbbr: 'hcq',
            nameEn: 'huichuanqu',
            level: '001',
            children: null,
          },
          {
            code: '520304',
            name: '播州区',
            nameAbbr: 'bzq',
            nameEn: 'bozhouqu',
            level: '001',
            children: null,
          },
          {
            code: '520322',
            name: '桐梓县',
            nameAbbr: 'tzx',
            nameEn: 'tongzixian',
            level: '001',
            children: null,
          },
          {
            code: '520323',
            name: '绥阳县',
            nameAbbr: 'syx',
            nameEn: 'suiyangxian',
            level: '001',
            children: null,
          },
          {
            code: '520324',
            name: '正安县',
            nameAbbr: 'zax',
            nameEn: 'zhenganxian',
            level: '001',
            children: null,
          },
          {
            code: '520325',
            name: '道真仡佬族苗族自治县',
            nameAbbr: 'dzglzmzzzx',
            nameEn: 'daozhengelaozumiaozuzizhixian',
            level: '001',
            children: null,
          },
          {
            code: '520326',
            name: '务川仡佬族苗族自治县',
            nameAbbr: 'wcglzmzzzx',
            nameEn: 'wuchuangelaozumiaozuzizhixian',
            level: '001',
            children: null,
          },
          {
            code: '520327',
            name: '凤冈县',
            nameAbbr: 'fgx',
            nameEn: 'fenggangxian',
            level: '001',
            children: null,
          },
          {
            code: '520328',
            name: '湄潭县',
            nameAbbr: 'mtx',
            nameEn: 'meitanxian',
            level: '001',
            children: null,
          },
          {
            code: '520329',
            name: '余庆县',
            nameAbbr: 'yqx',
            nameEn: 'yuqingxian',
            level: '001',
            children: null,
          },
          {
            code: '520330',
            name: '习水县',
            nameAbbr: 'xsx',
            nameEn: 'xishuixian',
            level: '001',
            children: null,
          },
        ],
      },
      {
        code: '520200',
        name: '六盘水市',
        nameAbbr: 'lpss',
        nameEn: 'liupanshuishi',
        level: '010',
        children: [
          {
            code: '520281',
            name: '盘州市',
            nameAbbr: 'pzs',
            nameEn: 'panzhoushi',
            level: '001',
            children: null,
          },
          {
            code: '520221',
            name: '水城县',
            nameAbbr: 'scx',
            nameEn: 'shuichengxian',
            level: '001',
            children: null,
          },
          {
            code: '520201',
            name: '钟山区',
            nameAbbr: 'zsq',
            nameEn: 'zhongshanqu',
            level: '001',
            children: null,
          },
          {
            code: '520203',
            name: '六枝特区',
            nameAbbr: 'lztq',
            nameEn: 'liuzhitequ',
            level: '001',
            children: null,
          },
        ],
      },
    ],
  },
]


const litleData = [
  {
    code: '520000',
    name: '贵州省',
    nameAbbr: 'gzs',
    nameEn: 'guizhousheng',
    level: '100',
    children: [
      {
        code: '522700',
        name: '黔南布依族苗族自治州',
        nameAbbr: 'qnbyzmzzzz',
        nameEn: 'qiannanbuyizumiaozuzizhizhou',
        level: '010',
        children: [
          {
            code: '522728',
            name: '罗甸县',
            nameAbbr: 'ldx',
            nameEn: 'luodianxian',
            level: '001',
            children: null,
          },
        ],
      },
    ],
  },
  {
    code: '340000',
    name: '安徽省',
    nameAbbr: 'ahs',
    nameEn: 'anhuisheng',
    level: '100',
    children: [
      {
        code: '341300',
        name: '宿州市',
        nameAbbr: 'szs',
        nameEn: 'suzhoushi',
        level: '010',
        children: [
          {
            code: '341321',
            name: '砀山县',
            nameAbbr: 'dsx',
            nameEn: 'dangshanxian',
            level: '001',
            children: null,
          },
        ],
      },
    ],
  },
]

// const provinceData = [['2344', '重庆市'], ['555', '四川省']]
// const cityData = {
//   2344: [['2344', '重庆市']],
//   555: [['123', '成都市'], ['1234', '南充市']],
// }
// const countyData = {
//   2344: [['444', '南岸区'], ['4445', '渝北区']],
//   123: [['5556', '武侯区'], ['5555', '武侯县']],
//   1234: [['6666', '南充区'], ['7666', '南充县']],
// }
function formartGeoInfo(geoData) {
  console.log('0--')
  const provinceData = []
  const cityData = {}
  const countyData = {}
  const formartData = {
    province: provinceData,
    city: cityData,
    county: countyData,
  }
  geoData.map((item, index) => {
    // console.log(item, index)
    provinceData.push([item.code, item.name])
    if (item.children) {
      cityData[item.code] = []
      item.children.map((childrenItem, childrenIndex) => {
        cityData[item.code].push([childrenItem.code, childrenItem.name])
        if (childrenItem.children) {
          countyData[childrenItem.code] = []
          childrenItem.children.map((grandsonItem, grandsonIndex) => {
            countyData[childrenItem.code].push([grandsonItem.code, grandsonItem.name])
          })
        }
      })
    }
  })

  return formartData
}

const res = formartGeoInfo(testValue)
console.log('-----------------------')
console.log(res.county)

export default res
